"use strict";var b=Object.defineProperty;var z=Object.getOwnPropertyDescriptor;var X=Object.getOwnPropertyNames;var Z=Object.prototype.hasOwnProperty;var ee=(o,e)=>{for(var t in e)b(o,t,{get:e[t],enumerable:!0})},te=(o,e,t,r)=>{if(e&&typeof e=="object"||typeof e=="function")for(let n of X(e))!Z.call(o,n)&&n!==t&&b(o,n,{get:()=>e[n],enumerable:!(r=z(e,n))||r.enumerable});return o};var re=o=>te(b({},"__esModule",{value:!0}),o);var me={};ee(me,{default:()=>O});module.exports=re(me);var E=require("@raycast/api");var w=require("@raycast/api");function d(o){return new Promise(e=>setTimeout(e,o))}function l(o){return o.replace(/'/g,"'\\''")}var x=require("node:child_process"),F=require("node:crypto"),C=require("node:util");var T=(0,C.promisify)(x.exec),y={WINDOW_ID_QUERY:2e3,WINDOW_TITLE_QUERY:1e3,APP_LAUNCH_POLL:1500,APP_LAUNCH_POLL_INTERVAL:100,WINDOW_CREATION_DELAY:300};function oe(o,e){return new Promise(t=>{let r=!1,n=null,s=setTimeout(()=>{r||(r=!0,n?.kill("SIGKILL"),t(""))},e);n=(0,x.exec)(o,(a,c)=>{r||(r=!0,clearTimeout(s),t(a?"":c))})})}function m(o){if(!/^[\w\s\-.]+$/.test(o))throw new Error(`Unsafe app name: "${o}". App name must contain only alphanumerics, spaces, dashes, underscores, and dots.`)}function ne(o){if(!o.startsWith("/")&&!o.startsWith("~")&&!o.startsWith("."))throw new Error(`Invalid path: "${o}". Path must be absolute or start with ~`);if(/[`$;|&><]/.test(o))throw new Error(`Unsafe path: "${o}". Path contains potentially dangerous shell characters.`)}function N(o){if(!Number.isFinite(o))throw new Error(`Invalid window ID: ${o}. Window ID must be a finite number.`)}function W(o,e){return oe(`osascript -e '${l(o)}'`,e)}var k={getWindowIds:o=>(m(o),`tell application "${o}"
  if (count of windows) > 0 then
    get id of every window
  else
    return ""
  end if
end tell`),getWindowTitle:(o,e)=>(m(o),N(e),`tell application "${o}"
  repeat with w in windows
    if id of w is ${e} then
      return name of w
    end if
  end repeat
end tell`),quitApp:o=>(m(o),`tell application "${o}" to quit`),closeWindowViaSystemEvents:(o,e)=>(m(o),N(e),`tell application "System Events"
  if exists process "${o}" then
    tell process "${o}"
      set windowList to every window
      repeat with w in windowList
        if id of w is ${e} then
          click button 1 of w
          return
        end if
      end repeat
    end tell
  end if
end tell`),closeWindowViaApp:(o,e)=>(m(o),N(e),`tell application "${o}"
  set windowList to every window
  repeat with w in windowList
    if id of w is ${e} then
      close w
      return
    end if
  end repeat
end tell`)},A=class{getAppName(e){let t=e.path.replace(/\.app$/,"").split("/").pop();if(!t)throw new Error("Could not extract app name from path");return t}async isAppRunning(e){m(e);try{let{stdout:t}=await T(`pgrep -x '${l(e)}' 2>/dev/null || true`);return t.trim().length>0}catch{return!1}}async getWindowIds(e){let t=await W(k.getWindowIds(e),y.WINDOW_ID_QUERY);if(!t.trim())return[];let r=t.trim().split(",").map(n=>Number.parseInt(n.trim(),10)).filter(n=>!Number.isNaN(n));return r.length>0&&console.log(`  Found ${r.length} windows for ${e}`),r}async getWindowTitle(e,t){return(await W(k.getWindowTitle(e,t),y.WINDOW_TITLE_QUERY)).trim()||void 0}async waitForAppToLaunch(e){let t=Math.ceil(y.APP_LAUNCH_POLL/y.APP_LAUNCH_POLL_INTERVAL);for(let r=0;r<t;r++){if(await this.isAppRunning(e)){await d(y.WINDOW_CREATION_DELAY);return}await d(y.APP_LAUNCH_POLL_INTERVAL)}}createTrackedWindow(e,t,r,n,s){return{id:(0,F.randomUUID)(),systemWindowId:n,itemId:e.id,appName:t,windowTitle:s??t,type:e.type,trackingMode:r,launchedAt:Date.now()}}async captureBeforeState(e){let t=this.getAppName(e),[r,n]=await Promise.all([this.isAppRunning(t),this.getWindowIds(t)]);return console.log(`[${t}] Before: running=${r}, windows=${n.join(",")||"none"}`),{item:e,wasRunning:r,windowIdsBefore:n,appName:t}}async launchOnly(e){let t=this.getAppName(e);m(t),ne(e.path),console.log(`[${t}] Launching...`),await T(`open -a '${l(e.path)}'`)}async captureAfterState(e){let{item:t,wasRunning:r,windowIdsBefore:n,appName:s}=e;r?await d(y.WINDOW_CREATION_DELAY):await this.waitForAppToLaunch(s);let a=await this.getWindowIds(s),c=a.filter(u=>!n.includes(u));if(console.log(`[${s}] After: windows=${a.join(",")||"none"}, new=${c.length}`),c.length>0){console.log(`[${s}] Using WINDOW-LEVEL tracking`);let u=await Promise.all(c.map(p=>this.getWindowTitle(s,p)));return c.map((p,i)=>this.createTrackedWindow(t,s,"window",p,u[i]))}return r?(console.log(`[${s}] Already running - skipping tracking`),[]):(console.log(`[${s}] Using APP-LEVEL tracking`),[this.createTrackedWindow(t,s,"app",0)])}async launch(e){try{let t=await this.captureBeforeState(e);return await this.launchOnly(e),await this.captureAfterState(t)}catch(t){throw new Error(`Failed to launch ${e.name}: ${t instanceof Error?t.message:String(t)}`)}}async close(e){for(let t of e)try{t.trackingMode==="app"?await this.closeApp(t.appName):await this.closeWindow(t.appName,t.systemWindowId)}catch(r){let n=t.trackingMode==="app"?"app":"window";console.error(`Failed to close ${n} ${t.appName}:`,r)}}async closeApp(e){m(e),console.log(`Quitting ${e} (app-level)`);try{await W(k.quitApp(e),2e3)}catch{await this.forceQuitApp(e)}}async getAppPIDs(e){m(e);try{let{stdout:t}=await T(`pgrep -x '${l(e)}' 2>/dev/null || true`);return t.split(`
`).map(r=>r.trim()).filter(r=>r.length>0).map(r=>Number(r)).filter(r=>!Number.isNaN(r))}catch{return[]}}async forceQuitApp(e){let t=await this.getAppPIDs(e);if(t.length===0){console.warn(`No running processes found for "${e}" to force quit.`);return}t.length>1&&console.warn(`Multiple (${t.length}) processes found for "${e}". All will be killed. This may affect other running instances.`);for(let r of t){if(!Number.isInteger(r)||r<=0){console.warn(`Invalid PID ${r} for "${e}", skipping`);continue}try{await T(`kill ${r}`)}catch(n){console.error(`Failed to kill PID ${r} for "${e}":`,n)}}}async closeWindow(e,t){console.log(`Closing window ${t} of ${e}`);try{await W(k.closeWindowViaSystemEvents(e,t),2e3);return}catch{}await W(k.closeWindowViaApp(e,t),2e3)}async verifyWindows(e){let t=this.groupByApp(e),r=[];for(let[n,s]of t)try{if(!await this.isAppRunning(n))continue;let c=s.filter(p=>p.trackingMode==="app");r.push(...c);let u=s.filter(p=>p.trackingMode==="window");if(u.length>0){let p=await this.getWindowIds(n),i=u.filter(g=>p.includes(g.systemWindowId));r.push(...i)}}catch(a){console.error(`Error verifying windows for ${n}:`,a)}return r}groupByApp(e){let t=new Map;for(let r of e){let n=t.get(r.appName)||[];n.push(r),t.set(r.appName,n)}return t}};var M=require("node:child_process"),R=require("node:crypto"),B=require("node:fs"),Y=require("node:util"),Q=require("@raycast/api");var U=(0,Y.promisify)(M.exec),I=class{async getFinderWindowIds(){try{let{stdout:e}=await U(`osascript -e 'tell application "Finder" to get id of every window'`);return e.trim()?e.trim().split(", ").map(t=>Number.parseInt(t.trim(),10)).filter(t=>!Number.isNaN(t)):[]}catch{return[]}}async launch(e){try{if(!(0,B.existsSync)(e.path))throw new Error(`Path does not exist: ${e.path}`);let t=await this.getFinderWindowIds();return await(0,Q.open)(e.path),await d(1500),(await this.getFinderWindowIds()).filter(s=>!t.includes(s)).map(s=>({id:(0,R.randomUUID)(),systemWindowId:s,itemId:e.id,appName:"Finder",windowTitle:e.name,type:e.type,trackingMode:"window",launchedAt:Date.now()}))}catch(t){throw new Error(`Failed to launch ${e.name}: ${t instanceof Error?t.message:String(t)}`)}}async close(e){for(let t of e)if(!(typeof t.systemWindowId!="number"||!Number.isFinite(t.systemWindowId)))try{await U(`osascript -e 'tell application "Finder" to close window id ${t.systemWindowId}' 2>/dev/null || true`)}catch{}}async verifyWindows(e){try{let t=await this.getFinderWindowIds();return e.filter(r=>t.includes(r.systemWindowId))}catch{return[]}}};var V=require("node:child_process"),H=require("node:crypto"),j=require("node:util");var D=(0,j.promisify)(V.exec),P=class{async getTerminalWindowIds(){try{let e=`
        tell application "Terminal"
          get id of every window
        end tell
      `,{stdout:t}=await D(`osascript -e '${l(e)}' 2>/dev/null || echo ""`),r=t.trim();return r?r.split(", ").map(n=>Number.parseInt(n.trim(),10)).filter(n=>!Number.isNaN(n)):[]}catch(e){return console.error("Error getting Terminal window IDs:",e),[]}}async launch(e){try{let t=await this.getTerminalWindowIds(),n=l(`
        on run argv
          tell application "Terminal"
            activate
            do script (item 1 of argv as text)
          end tell
        end run
      `);return await D(`osascript -e '${n}' '${l(e.path)}'`),await d(500),(await this.getTerminalWindowIds()).filter(c=>!t.includes(c)).map(c=>({id:(0,H.randomUUID)(),systemWindowId:c,itemId:e.id,appName:"Terminal",windowTitle:e.name,type:e.type,trackingMode:"window",launchedAt:Date.now()}))}catch(t){throw new Error(`Failed to launch ${e.name}: ${t instanceof Error?t.message:String(t)}`)}}async close(e){for(let t of e)if(!(typeof t.systemWindowId!="number"||!Number.isFinite(t.systemWindowId)))try{let r=`
          tell application "Terminal"
            set windowList to every window
            repeat with w in windowList
              if id of w is ${t.systemWindowId} then
                close w
                return
              end if
            end repeat
          end tell
        `;await D(`osascript -e '${l(r)}' 2>/dev/null || true`)}catch(r){console.error(`Failed to close Terminal window ${t.systemWindowId}:`,r)}}async verifyWindows(e){try{let t=await this.getTerminalWindowIds();return e.filter(r=>t.includes(r.systemWindowId))}catch(t){return console.error("Error verifying Terminal windows:",t),[]}}};var K=require("@raycast/api"),v=class{async launch(e){try{return await(0,K.open)(e.path),[]}catch(t){throw new Error(`Failed to launch ${e.name}: ${t instanceof Error?t.message:String(t)}`)}}async close(){}async verifyWindows(){return[]}};var se=process.env.RAYCAST_APP_INIT_DELAY_MS?Number(process.env.RAYCAST_APP_INIT_DELAY_MS):1500,L=new A,ie=new Map([["app",L],["file",new I],["folder",new I],["url",new v],["terminal",new P]]);function ae(o,e){let t=new Map;for(let r of o){let n=e(r),s=t.get(n)||[];s.push(r),t.set(n,s)}return t}async function ce(o){let e=ie.get(o.type);if(!e)throw new Error(`Unknown item type: ${o.type}`);return e.launch(o)}async function pe(o){console.log("Phase 1: Capturing before-state...");let e=await Promise.all(o.map(r=>L.captureBeforeState(r).catch(n=>(console.error(`Error capturing before-state for ${r.name}:`,n),null))));return console.log("Phase 2: Launching all apps..."),await Promise.all(o.map(r=>L.launchOnly(r).catch(n=>{console.error(`Error launching ${r.name}:`,n)}))),console.log("Phase 3: Waiting for apps to initialize..."),await d(se),console.log("Phase 3: Capturing after-state..."),(await Promise.all(e.map(r=>r?L.captureAfterState(r).catch(n=>(console.error("Error capturing after-state:",n),[])):Promise.resolve([])))).flat()}async function de(o){let e=await Promise.all(o.map(async n=>{try{return{success:!0,windows:await ce(n)}}catch(s){let a=s instanceof Error?s.message:String(s);return console.error(`Error launching ${n.name}:`,s),{success:!1,error:a}}})),t=e.filter(n=>n.success).flatMap(n=>n.windows),r=e.filter(n=>!n.success).map(n=>n.error);return{windows:t,errors:r}}async function q(o,e){if(o.length===0)return await(0,w.showHUD)("Workspace is empty"),[];let t=await(0,w.showToast)({style:w.Toast.Style.Animated,title:"Launching workspace...",message:e}),r=[],n=[],s=o.filter(i=>i.type==="app"),a=o.filter(i=>i.type!=="app"),c=ae(s,i=>i.delay||0),u=Array.from(c.keys()).sort((i,g)=>i-g);console.log(`Launching ${s.length} apps in ${u.length} groups + ${a.length} other items`);for(let i of u){i>0&&(console.log(`Waiting ${i}ms...`),await d(i));let g=c.get(i)||[];if(g.length!==0){console.log(`
=== Launching ${g.length} apps (delay: ${i}ms) ===`);try{let h=await pe(g);r.push(...h),t.message=`${r.length} items tracked`}catch(h){n.push(h instanceof Error?h.message:String(h)),console.error(`Error in delay group ${i}:`,h)}}}if(a.length>0){console.log(`
=== Launching ${a.length} non-app items ===`);let i=await de(a);r.push(...i.windows),n.push(...i.errors)}let p=o.length-n.length;return n.length===0?(t.style=w.Toast.Style.Success,t.title="Workspace launched successfully",t.message=`All ${p} items opened`,await(0,w.showHUD)(`Opened ${p} items from "${e}"`)):(t.style=w.Toast.Style.Failure,t.title="Workspace launched with errors",t.message=`${p}/${o.length} items opened, ${n.length} failed`,await(0,w.showHUD)(`${p}/${o.length} items opened. ${n[0]}`)),console.log(`Collected ${r.length} tracked windows`),r}var f=require("node:fs");var G=require("node:os"),S=require("node:path"),$=(0,S.join)((0,G.homedir)(),".config","respace-raycast"),_=(0,S.join)($,"workspaces.json"),be=(0,S.join)($,"sessions.json");function le(){(0,f.existsSync)($)||(0,f.mkdirSync)($,{recursive:!0})}function we(){if(le(),!(0,f.existsSync)(_))return{workspaces:[]};try{let o=(0,f.readFileSync)(_,"utf-8");return JSON.parse(o)}catch(o){return console.error("Error reading workspaces:",o),{workspaces:[]}}}function J(){return we().workspaces}function ue(o,e){let t=e.toLowerCase(),r=o.find(n=>n.name.toLowerCase()===t);return r||o.find(n=>n.name.toLowerCase().includes(t))}async function O(o){let{workspaceName:e}=o.arguments;if(!e){await(0,E.showHUD)("\u274C Please provide a workspace name");return}let t=J(),r=ue(t,e);if(!r){await(0,E.showHUD)(`\u274C Workspace "${e}" not found`);return}await(0,E.showHUD)(`\u{1F680} Opening ${r.name}...`),await q(r.items,r.name)}
