#!/usr/bin/env zsh

# Symlinks ~/Downloads to iCloud Downloads folder
# Only runs on macOS. Backs up existing Downloads to dotfiles backup dir.

TARGET="$HOME/Downloads"
SOURCE="$HOME/Library/Mobile Documents/com~apple~CloudDocs/Downloads"

if [ "$(uname)" != "Darwin" ]; then
  echo "Skipping Downloads pointing on non-macOS platform"
  exit 0
fi

if [ ! -h "$TARGET" ]; then
  if [ -d "$TARGET" ]; then
    mv "$TARGET" "$HOME/.dotfiles/backup/Downloads"
  fi

  ln -s "$SOURCE" "$TARGET"
  chmod -h 700 "$TARGET"
fi
